version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD: ecom_password
      POSTGRES_DB: ecom_db
    ports:
      - "5434:5432"
    volumes:
      - ecommerce_pgdata:/var/lib/postgresql/data

  ecommerce-service:
    build: .
    container_name: ecommerce-service
    environment:
      - PORT=4001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=ecom_user
      - DB_PASSWORD=ecom_password
      - DB_NAME=ecom_db
      - JWT_ACCESS_SECRET=super_secret_access_key_change_me
    depends_on:
      - postgres
    ports:
      - "4001:4001"

volumes:
  ecommerce_pgdata:
